### ISSUE TITLE
UPDATE DOCS

### ISSUE THREAD

**Issue by lukas-zech-software** [zachwinter/kaleidosync#7]
You missed in the `npm run build` script in the steps

Also detection if port 8001 is already in use would be really usefullndluf ( I have plenty dev server running)

If help is  I welcome will gladly throew a few of my hours of experience (TS,node,express,angular,wepack)  at this project

**Comment by zachwinter** [comment]
Thanks for opening this! Did you have to run the `build` script when following the "run locally" instructions? It should only be needed for a prod build. 

Port detection didn't seem necessary to me due to Spotify apps having predefined app / redirect URIs. What do you think would be the best way to go?
